### ISSUE TITLE
Currently no way to delete a storage-atom without using js/localStorage directly

### ISSUE THREAD

**Issue by danielytics** [alandipert/storage-atom#5]
It would be great if there was a way to delete a storage-atom from local storage without having to resort to JS.

Since the workaround is straightforward, @alandipert feel free to close this issue if this isn't something you care to add.

```clojure
(def prefs (local-storage (atom {}) :prefs))
(.removeItem js/localStorage ":prefs")
```

**Comment by ninjudd** [comment]
Hey guys. I took a different approach in my implementation based on my need to support clearing all values, and to ensure that remove works correctly with multiple browser windows. I've submitted a pull request in #6. I'd love to hear your feedback!
